#????????
server:
  port: 9999

#?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project01?serverTimezone=GMT%2B8
    username: root
    password: 010830

  #Redis??,?????????????
  redis:
    port: 6379
    host: localhost

# sql??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Redis??


